language: erlang
otp_release:
  - 17.5
sudo: false
addons:
  postgresql: "9.4"
before_install:
  - wget http://s3.hex.pm/builds/elixir/$ELIXIRVERSION.zip
  - unzip -d elixir $ELIXIRVERSION.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - git clone https://github.com/hexpm/hex_web.git
  - (cd hex_web; mix deps.get; MIX_ENV=hex mix compile; cd ..)
  - mix deps.get
  - MIX_ENV=test mix deps.compile
script:
  - MIX_ENV=test mix compile
  - HEX_WEB_DIR=hex_web mix test
env:
  matrix:
    - ELIXIRVERSION=v1.0.5
    - ELIXIRVERSION=v1.1.0
matrix:
  include:
    - otp_release: 18.1
      env: ELIXIRVERSION=master
notifications:
  recipients:
    - eric.meadows.jonsson@gmail.com
